name:                FunctionalHilbert
version:             0.1.0.0
github:              "kanashimia/Throw-Away-Projects/blob/master/FunctionalHilbert"
license:             BSD3
author:              "Ursol Nikita"
maintainer:          "nikita20001116@google.com"
copyright:           "2020 Ursol Nikita"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kanashimia/Throw-Away-Projects/blob/master/FunctionalHilbert/README.md>

dependencies:
- base >= 4.7 && < 5
- diagrams >= 1.4
- diagrams-rasterific == 1.4.*
- diagrams-svg
- diagrams-lib
- palette
- colour

library:
  source-dirs: src

executables:
  FunctionalHilbert:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FunctionalHilbert
